services:
  mysql:
    image: mysql:8.4
    container_name: flight_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flight_booking
      MYSQL_USER: flight_user
      MYSQL_PASSWORD: flight_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: flight_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flight_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: ./backend
    container_name: flight_backend
    restart: unless-stopped
    environment:
      PORT: 5000
      NODE_ENV: development
      JWT_SECRET: super_interview_secret_change_me
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: flight_booking
      MYSQL_USER: flight_user
      MYSQL_PASSWORD: flight_pass
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      SUPPLIER_BASE_URL: https://uthaotrip.com/api
      FRONTEND_URL: http://localhost:5173
    volumes:
      - svg_exports:/app/storage/exports
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: flight_frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
  svg_exports:
